### PR TITLE
Style: Clang format everything

### PR DESCRIPTION
**Pull request by JJL772**
Some files fell out of date with our formatting standards, so I re-applied it to the codebase.

This PR is based on #26 to avoid rebasing pain later on. That PR will need to be merged first, then this PR can be marked as ready.

### CODE REVIEW

**Comment by klauer** [comment]
Would it be worth adding a GitHub action along the lines of https://github.com/jidicula/clang-format-action to validate that PRs follow the style requirements? (I admittedly did not verify this specific action, but it looks appropriate on the surface)

**Comment by JJL772** [comment]
Yeah I think so. I need to totally overhaul CI for this project at some point, I'll add that to my TODO list.

**Comment by JJL772** [comment]
Forgot to mark this as ready!

**Review by klauer — APPROVED** [review]
LGTM ✅

**Pull request merged**
