### PR TITLE
ENH: add find_terminal tool and EL2794 support

### PR DESCRIPTION
**Pull request by klauer**
## `find_terminal.py`
This is part of the effort to better understand the library and get the EL2794 in (the latter being a comparatively simple task...)

Starting with a tool to scrape the xml files better in order to add a given terminal:

```
$ python find_terminals.py EL2794
EL2794 rev #x00100000
  - RxPdo
   0. Channel 1 (1 words @ 5632 mandatory fixed)
      - Output: 1 bits (BOOL)
   1. Channel 2 (1 words @ 5633 mandatory fixed)
      - Output: 1 bits (BOOL)
   2. Channel 3 (1 words @ 5634 mandatory fixed)
      - Output: 1 bits (BOOL)
   3. Channel 4 (1 words @ 5635 mandatory fixed)
      - Output: 1 bits (BOOL)
   * Mapping 'All PDOs'
     pdo_in_size=[] pdo_out_size=[1, 1, 1, 1] / not in terminals.json
```

Considers the different possible syncmanager mappings and sees if there's a match in `terminals.json`. Will be using this (or a fixed up version of it) to gather information for new terminals.

## EL2794 support

* Added EL2794 support using the above information
* Confirmed it works with @mbosum and Ricardo's test rail (`ioc-peppex-test`)

Think I'm missing anything here, @JJL772 or @mcb64 ?

### CODE REVIEW

**Review by mcb64 — APPROVED** [review]
Please tell me terminals.h is a generated file though.  Because otherwise, NUM_TERMINALS gives me the heebie-jeebies.  I'd much rather see it defined as (sizeof(g_pTerminalInfos)/sizeof(g_pTerminalInfos[0])) and no size on the g_pTerminalInfos array.

**Comment by klauer** [comment]
It is, @mcb64 : https://github.com/slaclab/epics-ek9000/blob/6dedab47cad23ce7d802503ba72868667bbea3c4/ek9000App/src/scripts/Makefile#L11-L12

Though I agree letting the compiler take care of it would be preferable

**Comment by JJL772** [comment]
I suggest adding an `ArraySize` template like this to handle that:

```cpp
template<class T, size_t N>
size_t ArraySize(T(&arr)[N]) {
    return N;
}
```

Should work in old C++ standards too

**Review by JJL772 — APPROVED** [review]

**Comment by klauer** [comment]
I'll open an issue for the array size thing and go ahead with this one. 👍

**Pull request merged**
