### PR TITLE
Fix locking issue.

### PR DESCRIPTION
**Pull request by mcb64**
If we return from getEK9000IO with an error, we hold the lock and everything dies.  Release the lock, and autoconnect will eventually fix us up.

### CODE REVIEW

**Comment by mcb64** [comment]
Showing my inexperience with git. ;-)  This is a pretty simple change due to holding a lock after returning from a routine with an error.  This should be pulled into slac-trunk as well, but for now, I'm just asking it to be pulled into master.  Most of the rest in the history is my struggling with git!

**Review by klauer — APPROVED** [review]
Nice catch!

**Comment by mcb64** [comment]
Well, when everything comes to a screaming halt after a single error, it's pretty easy to figure out that there is a problem. ;-)

**Comment by klauer** [comment]
Did a squash merge to combine those extraneous commits - so the repo history will be a bit cleaner.

**Pull request merged**
